version: '3.8'

services:
  db:
    image: postgres:15
    container_name: my_pgdbss
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgreuser
      POSTGRES_DB: SprintStackDB
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
